### ISSUE TITLE
I get Error: Cannot find module 'node-windows'

### ISSUE THREAD

**Issue by futurewebsites** [MacroMan/DPDLocalPrinter#2]
Hi Sorry to comment again so soon - I have installed node.js ran npm install and can see node-windows installing globally however when I run node install.js I get the following Error: Cannot find module 'node-windows' 

I have also tried running npm install node-windows -g  and then retried node install.js and also tried npm link node-windows all done in C:\Program Files\DPDLocalPrinter

**Comment by MacroMan** [comment]
Try installing node-windows locally (without -g) as well and see if that helps.

It's been a while since I touched this, so I'm a little rusty, so please bear with me while I help you.

**Comment by futurewebsites** [comment]
No worries I am a mac user trying to do windows so the same goes :) - when trying node-windows without the g I get **EPERM, operation not permitted** so looks like a windows issue I think its running windows 7 professional if that helps

**Comment by MacroMan** [comment]
I've just gone through my notes and I did have to install node-windows locally too.
I've not seen that error before, so I can't really help with that, but once solved and installed locally, it should work for you. On Windows 7 too, so it can't be the full issue.

**Comment by MacroMan** [comment]
As I haven't heard back for a while, I'll close this issue, but feel free to re-open if you're still stuck
